apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCnRNVn27sddtvCdg8cKAP6cJ3wDBmubIfzGA0ggR9Zm1OZ5jFe3PFkuSySWDr6U+9hSCA8qal6TPdHYD9cope9SQC4SBjxuQSMaACQed7hi4Ubni+F1yrRVnT6v8pSO0klS6HsTF/w64bJxwqBooJKKBcRMkEUJPlD1UYUETyjIrgmdDT4eYgeHRShtkLWmEZ7SAdas4Niwylmjt/4VuiPqbnXXdNoebPeRY5gSRysO2B5z4HQOBn/qm71XnOXGJDZ+t55ICBrix+iRLNpLtoWxEJZAukKKBD4rf/ksN4mWaEQCOVKSDunO1nwCneEJoxeoFe4wG5QFTzSJN7MsGSUrLwS31j+q72K3LnoOmxccM5NLPrVz/JmqQA7m6SS6kJ4/4n1MjGxIq7vm2OL/dd0HDoPudUBUUsqO5wG6Jd0IQVsiim+9ZqvD71hSz7IHKDqWDSOGbrHTFOmDDCIHYddLq4d0p+O6jurvCM/g6P1eR5Dr5/wQz2BpUsjVACIK9nQzapJ+LBT9aE4WdR71Q8zetXSyiRozbCyNyAhy3IDxeoHjVFnpgE732QjF+WowKmCnbyO/H8S3exZkasDtJamTMHTI98PMujID9oTd5SuMDu9r8LXEmyG3iPcmYqI6KA1kF+JTIOIP4owBhxfVElBVHQzwspNTuTMBl4e0bQyx09Lw+AhrcRj2TFN5UStAj1KK9wfGWRvyEQhA8mxyAx9RtrrROusL0qxv4DHLDQl2FyNT0DxPzPHHPUUop8mgY6I0MlUDn9G71s=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

