apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgC3FPoeS9i5ZmdTfa7OEs2l6hQuF5nRyPqTvHD7N9GrDYbWj6zbrLDgvxj0ZVkgGZIUhWMkIX9ydtOk8osezpNxZl7s68RJ7G31kFek+u9sCE4/XmA9HqMSedTV7b0qzdI5LO2HlM4FetWrgQn+ZYKprBg6xin1aCUFk9rHpC1mImlIE5GpV5YK8WeTbN8NVxOcWNykeDY/1IvhOVcOjTAKEj9X2Qxr+goK3bMFKhEIIK6CULoEV2R0C2fKUSntKcO45aNbPXYnwXIj7RtL5KzGcE3ftkm/0h9SrYg2R2V3Ton3HtLBaPAo6BE5yQidL2dlBT/L1tvzPvkQi+p2aZNjEYBSNo3AwV7GOrGeA0MEyBSAhXLbk3bJHCSVqFWUgoUDbiak2LpBeaeiTb+WXGr+z1BdVuEnXF2JsFAi2V8JzRRARhwDeLLsPLlhpWvcDh27Pl12SGHk/0/4Z2qQ3rJ8AQggywqcTYejmmug7R1UOrDspcsWm2IzcxkZxIQ8HyuclTcGEKn22ok+m18Q+tt/UZz15slxpQTvoWDwkOIaRvuqQLqp6jeeWsOU0koF2OIQGhRTj+shmZAdx1L0QAQu1jp1BZFv+LXApNRs1okmjvcSnz8/ricscvu12ILUjJGW7OQPOVRJiUCOztVF/Ri3IdZ41qTbfqvRb5B4Aza5URcPscfclrvbHClZzSeJ8V1Fo48sKbGihOtTUv4z3mWEPY8HRjcb2l/LLTxxPzPnsUO9cqKW5DDFK2nR6j/zWSb9AoZNbzKOx0I=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
