apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAxlKdSGgLkpsSnItctRIfwbKD3Rf69SUazszvukff8fuwN3Hr05lPS+NQmqtl2C3ICopONEGt77gAz5KGDekcFt5yrHk1CuPMIt72L9QHP8Zu3BTigwUZs+xGIvzPIQ6DWmkxtR+mctHOvDh1v3qvKDFZb70rydcHmnclauK1lHk/mu2R3cGW6pjdCCvf8uMyNzDeiJ1wovsWA45XwmYrx54EsOWY9vay/4gvZx77AyDefN/MJ/zUGwkg2PUZONu+Du6hBlsjAmzB7LmeaJvXSeqGqItohZvxwKimL6ZsQPcAX9m7rx/5iAlr+jKqQBAPpi4bPi+ZIiNekGAuWgz4hxitT+meEaSs2Zl3eAO9cSokgyuPKHBDsmzfRZWvD8nQjMvD9gASDqSFWTthtw19BaqJV9AnoEXNuPCO8POPlPd2vsy18lTweIOFF2cXeN/FlnydVYRrdDDvonl3GiV0mYi40RR+NLaeuEYswIQ++7Q9uaSVXA7qZWAzlSlOsqGhFOf/jSmQLEFxur07IyB2BOypXw3MVdvp2zyr/19zKf8z2hqsEROPevC1PncqrhkXV0iGTtmt8GluFCBJ4+cyvtYvkZYJEuiagpbCJhnYMSG8w8fJpEHBhddLyaXLiLOW/pl9rfCp2Ywt1mR8u2m3sJmKACOyEC7MY7g3Z4J6aW5JGUkS8J4O9Pa3FklJC2uQBhAEE8G2gS5rFUwCfAaG4sUS/KavkX+Ne5ULEBIyCcUhRkMXOAPsi+TI3QECXWuDJp8xUsg7+WhQ=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

