apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA6Vhdc38INnuXwEWlqifz2437RmF/JgMVv73P3mHEmQ2dNXD+AKjw+uaIb2aMrjwbUfa1erT8GQicxCoCu55v+sMtnD9hJZAj/6FlPEK4q+n75x+74kMJvvOhyl7i+mijCNqHFir/v4gXBMyLDCCW+HVaI8KhbaWR4MLjzCqW/ry7+IDdNdpV+I/YWiTuuFaFJ1MwDghyrQfFgG+wCdYeL5dU0W+zFwJuGx3nSECBvLyCxgHNHN+ah+VyVCDcb2XMFNVzu5ILUy/sn3Y5u8S0kinXx7KKR01LiLmLJgh4/eRJXsETk1I7VSvnOe1noWD+6pgY9jhk+eSZMNiCoSdpzmZwKEqt6A7LPIAQd66sYJa+0GclYJwv6Fdx/YT3lb+1CD/kPext9c67mhZmL98AZQBjT7vuy+BLv/iOsLUWSXNhhI73JkxrENaCYZktJs3csWlfyb0FWU80yngSM1fAwYkjuO/iHQPyDzDfwpZoew3CLR9PSAGQNgwB/+eKXi33s8E9Iy7dSm0mLQmCT7CoSeN3FVsWWtkRjCZHaIF0eDQ3sEh8/GH+VNBNiPv05Z0i8eSEdife8Zu+zXrlVVfM+03VWys4E74dM/W+tmKYKfOXHbGTtdxy4Vmbm+AeAWNbEMBHK8Vfn9HMIekQXTuttU8Zgo/tErs5tvxfxLW8HcX8MhXU2JgbTZi28D+l/FtErwaTW8J94K/3+xqneLQEXZ+Fi/ML9x9QkMsQ+zcCZSuE+Dg8fPyh/TAa1ijdtr8cIFbl33GGMrPjkqF+vQ08oxL9n8zlYGSwGK2OyRJGHXuh12LCqiVf97PNMSxzDwExpY6y5u/PLiRMrHXjBQidiyAhsnJ4=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
