apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBH92QYzn8gg93K7c1YDG4f1jj+1SgFvF1YHaVztSdHCTwyy4Fk/rIdJ/ZbFEFim1dktw3tvZjqNnQQcBWP+RanUOVDMgs0hkDWOstrkv5QQ0MegKUnvyZrj/ee3Pek8NdV+5nKl0X59MNAjc81zJg3V1Hwo1kty4fPrUK9qKZ8lk9j8Kz51mu8TZ/W/7xGD6xJ4vrV3xElTF9PXus8CMUOyTSrPPWDlPg2lwcqVMkdQN8h+HbSxbT2/c0jcddWYC0+otqHzva4DshuQ1x72j6ff9t739tFUAtChL5ctI+1SgAC05Aap/D39mRYeKWAAnxAgDQL2JvemuU/Vr6H10bTbmJvp3UjNY4cn4goFHQlxZCqTJjkbDTDpfIHvMMS5+Euii8k+BhT5FXpI4fabnZaJeLdpayHOYRLSV6OaNWlHf7voVPCeoDTRnICjFaCWmQ6Za2eLMRzX26lQSIAj/sECRx99h0QkG5B1gS3dOjvwVPclNi1T+lItY2g2DASC2poUb3wI/n+RGDZ+a9pIkQ0G3w+yqaYfH7/oUWk3Y6cdq7/qeR0PSOJSsg+1dLp4aEvsD6aPZnKDwFQAVebKH3uEo5tYAJd0xUGmIFeGavnmPsxpvbISocyqER2oZBPs6qVafAw/PWoYme3D/5YW/3R6LaxnqCpl8EGC9Kfc9VMVS6gNkUQqYIRBt22rrEhoo0FUrNnVyIuHA3zkA9i2maqvbsWZuqLOZy/KSUj7wTyg5lXEPvawFyklmrrkqoobZt/xDJ38iWY1xyDqEPhdqbBakoZqzrD41xQN8C4ErdV4P4IYK1Qyu52AqawqtNjR8Ug/pRUaMtbmY8hokpLJHULVvuztzQ=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

