apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB9XevykGPXKqQA2bQy5A04QbNRrBRzsMSeaYAGzQpcZ+TzTiu+F6M6wd8xAkPRfQrd5StIhwQD9B/jJB0GnS8l4zpkbjbHb6H7PdZ4M3RN4dETnQCeJa/KNruDn1T8FMAnmAseW0T/0S1dvUqaKikVLhokzoTl0797iFJbCBhyPhiOSAVuzcfuVzXVHdc4LbcmPusx8spk1wumPkTAozmm6X3FtpCEETZgOwKc8PfuetpABCuR9g4MkGFva57qedjCZ4KZkUFc4XzxW9NbCxKFevAPAO/I84h7pm1ssMfT1Byg+zYY7WKyHAATi1ahjK52tmM2X6GJodt0bLucjejuSU6S5N2NDGVe5Uh8qBBUJWk7Rxl7nzhpytAfFLNQN9q3qDNKAzprAhfBV/pTJfIFeFHXVWpQLULhcUSrLDBoliWeLQKwwDVdP6KpK5S+eDJGzsMNAwkwyEH7RxqzMxCMjT4fPdHZFDBMBqH39mAUfqdoCSC/3rxkVPT+UO9Ma6NoRE9R6FBS2BrcKEWynABDke1HPHI28sD31mI93NvpFnFWzGGFoig1ZBRV4+Y5PaHrXU9vC96jC1SjHjMwpKtwPn+7MUVrI5RV8DSgqbwVbJzbTdxGrDnpvQN32NvLSHDDjzXseVI7eOy2qbXtqOzpIKBmHTiI8kKjDLoFWGqVEXu058VFpFLyzgi+RzFeFYJMnWQ6T3r50ZTOiGWtZ18gxd/vligr1JexrsdfdKnDx29+47L6vVpKDiPkn1/QDD3t9c72Q28m6iYF6dEu+JFLSeYq/gOJACU+PBxNz2v4O5VTMBbhKA1LX2+dtspinWwdNbUmRIFhAZHQEXGUWUGqWV/xybc=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

