apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: team-a
  labels:
    cluster-owner: marcellmartini
spec:
  compositionRef:
    name: cluster-aws
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    # version: "1.20"
    # minNodeCount: 2
  writeConnectionSecretToRef:
    namespace: team-a
    name: cluster
