apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps-reqs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-app-reqs
    repoURL: https://github.com/marcellmartini/crossplane-kubevela-argocd-demo
    targetRevision: presentation
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
